Update introduction.mdx
When trying to follow the existing introduction, I encountered an error that might suggest their is a missing step or a missing environment setup required, specifically access to the gpt-4o model. 
Diagnostic:  raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}